### ISSUE TITLE
Could not find function "dynamicFile"

### ISSUE THREAD

**Issue by nsleep** [systemPipeR/systemPipeShiny#84]
Version:
Ubuntu 18.04.5 LTS
R version 4.1.0 (2021-05-18)
systemPipeShiny 1.1.40

I have installed _systemPipeShiny_ and executed _spsInit()_, and installed lib*. 
When I clicked the _run app_ button, it gave an error.
This is more detailed information：
![console.pic](https://user-images.githubusercontent.com/23132161/118937298-f8239a00-b97f-11eb-844d-608f8eccaaba.png)
I find "dynamicFile" is called in the vs_rnaseq_dataUI function, but still don't know what happened.

**Comment by lz100** [comment]
We have made an update, so the `dynamicFile` function has been moved from {spsComps} on 0.3 to {systemPipeShiny} main package on 1.1.41. The reason you didn't find it is because you updated {spsComps} to 0.3. Install the Github version of SPS will solve the problem `remotes::install("systemPipeR/systemPipeShiny")`.

Always read the [NEWS.md](https://github.com/systemPipeR/systemPipeShiny/blob/master/NEWS.md). It may give you some clues of what's happening. 

Close this issue for now. If you have other problems, feel free to reopen it.
